name: Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17 (required by modern AGP)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Installs Android cmdline-tools + sdkmanager
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Install platform & build-tools that work for most projects.
      # If your project uses another version, change the 34.0.0/34 values.
      - name: Install SDK packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      # Build a DEBUG apk first (no signing needed)
      - name: Build Debug
        run: ./gradlew --no-daemon clean assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
